# Generated by Django 4.2.7 on 2025-07-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_department_alter_user_faculty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default=None, help_text='Upload a profile image.', null=True, upload_to='profile_pictures/', verbose_name='Profile Picture'),
        ),
    ]
