# Generated by Django 5.2.2 on 2025-08-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Format: +999999999 or 999-999-9999', max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_id',
            field=models.CharField(blank=True, help_text='6-20 character student identification. Auto-generated for Google users.', max_length=20, null=True, unique=True, verbose_name='Student ID'),
        ),
    ]
