# Generated by Django 5.2.2 on 2025-08-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_phone_number_alter_user_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='faculty',
            field=models.CharField(blank=True, help_text='Faculty or school name', max_length=100, verbose_name='Faculty'),
        ),
    ]
