# Generated by Django 4.2.7 on 2026-03-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_faculty_alter_user_is_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cancellation_warning_count',
            field=models.PositiveIntegerField(
                default=0,
                help_text='Total warning notices issued for late cancellations.'
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='late_cancellation_count',
            field=models.PositiveIntegerField(
                default=0,
                help_text='Number of late cancellations (less than policy notice period).'
            ),
        ),
    ]
