# Generated by Django 5.2.4 on 2025-07-20 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_room_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='building_type',
            field=models.CharField(choices=[('main', 'Main Building'), ('science', 'Science Building'), ('library', 'Library'), ('lab', 'Laboratory'), ('office', 'Office'), ('auditorium', 'Auditorium'), ('other', 'Other')], default='main', help_text='Type of building (e.g., Main, Science, Library, etc.)', max_length=20),
        ),
    ]
