# Generated by Django 5.2.4 on 2025-07-20 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_room_building_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='building_name',
            field=models.CharField(choices=[('A', 'Building A'), ('B', 'Building B'), ('C', 'Building C'), ('D', 'Building D'), ('E', 'Building E'), ('F', 'Building F'), ('G', 'Building G'), ('H', 'Building H'), ('I', 'Building I'), ('J', 'Building J'), ('other', 'Other')], default='A', help_text='Specific building name (e.g., Building A, B, etc.)', max_length=20),
        ),
    ]
