# Generated by Django 5.2.2 on 2025-07-25 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_room_building_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(help_text='Room number or code (can be duplicate)', max_length=50),
        ),
    ]
