# Generated by Django 5.2.2 on 2025-08-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_change_default_status_to_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='calendar_last_synced',
            field=models.DateTimeField(blank=True, help_text='Last time this booking was synced with Google Calendar', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='calendar_sync_enabled',
            field=models.BooleanField(default=True, help_text='Whether to sync this booking with Google Calendar'),
        ),
        migrations.AddField(
            model_name='booking',
            name='google_event_id',
            field=models.CharField(blank=True, help_text='Google Calendar event ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='google_event_link',
            field=models.URLField(blank=True, help_text='Google Calendar event link', null=True),
        ),
    ]
