# Generated by Django 5.2.2 on 2025-08-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_add_google_calendar_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='calendar_sync_enabled',
            field=models.BooleanField(default=False, help_text='Whether to sync this booking with Google Calendar'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='google_event_link',
            field=models.URLField(blank=True, help_text='Link to Google Calendar event', null=True),
        ),
    ]
