# Generated by Django 5.2.2 on 2025-08-02 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_alter_booking_calendar_sync_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(help_text='Announcement title', max_length=200)),
                ('content', models.TextField(help_text='Announcement content')),
                ('announcement_type', models.CharField(choices=[('general', 'General'), ('maintenance', 'Maintenance'), ('policy', 'Policy Update'), ('emergency', 'Emergency'), ('event', 'Event')], default='general', help_text='Type of announcement', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', help_text='Priority level', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the announcement is active')),
                ('show_until', models.DateTimeField(blank=True, help_text='Show announcement until this date (leave blank for indefinite)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Admin who created the announcement', on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'db_table': 'announcements',
                'ordering': ['-priority', '-created_at'],
                'indexes': [
                    models.Index(fields=['is_active', 'show_until'], name='announcement_active_show_until_idx'),
                    models.Index(fields=['announcement_type'], name='announcement_type_idx'),
                    models.Index(fields=['priority'], name='announcement_priority_idx'),
                ],
            },
        ),
    ]
