# Generated by Django 5.2.2 on 2025-08-03 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_add_announcement_table'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='announcement',
            new_name='announcemen_is_acti_13e55a_idx',
            old_name='announcement_active_show_until_idx',
        ),
        migrations.RenameIndex(
            model_name='announcement',
            new_name='announcemen_announc_b7733d_idx',
            old_name='announcement_type_idx',
        ),
        migrations.RenameIndex(
            model_name='announcement',
            new_name='announcemen_priorit_370592_idx',
            old_name='announcement_priority_idx',
        ),
    ]
