# Generated by Django 5.2.2 on 2025-10-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_rename_announcement_active_show_until_idx_announcemen_is_acti_13e55a_idx_and_more'),
    ]

    operations = [
        # Add the missing room_number field
        migrations.AddField(
            model_name='room',
            name='room_number',
            field=models.CharField(
                max_length=50,
                help_text='Room number or code (can be any text, duplicates allowed)',
                default='TBD'  # Temporary default for existing records
            ),
        ),
    ]
