# Generated by Django 5.2.2 on 2025-10-22 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_fix_room_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(help_text='Room number or code (can be any text, duplicates allowed)', max_length=50),
        ),
    ]
