# Generated by Django 5.2.2 on 2025-10-22 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_alter_room_room_number'),
        ('booking', '0014_remove_room_building_fields'),
    ]

    operations = [
    ]
