# Generated by Django 4.2.7 on 2026-01-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_merge_20251022_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='confirmed', help_text='Current booking status', max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='availability_status',
            field=models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable')], default='available', help_text='Current availability status', max_length=20),
        ),
    ]
