# Generated by Django 4.2.7 on 2026-03-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_alter_booking_status_alter_room_availability_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='availability_status',
            field=models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('unavailable', 'Unavailable')], default='available', help_text='Current availability status', max_length=20),
        ),
    ]
