# Generated by Django 4.2.7 on 2026-03-20

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_alter_room_availability_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='agreed_to_room_policy',
            field=models.BooleanField(default=False, help_text='Whether user agreed to room usage terms for this booking'),
        ),
        migrations.AddField(
            model_name='room',
            name='auto_status_updates',
            field=models.BooleanField(default=True, help_text='If enabled, status is automatically calculated from active bookings'),
        ),
        migrations.AddField(
            model_name='room',
            name='max_booking_capacity',
            field=models.PositiveIntegerField(default=1, help_text='Maximum attendees allowed for booking this room', validators=[MinValueValidator(1), MaxValueValidator(1000)]),
        ),
        migrations.AddField(
            model_name='room',
            name='min_booking_capacity',
            field=models.PositiveIntegerField(default=1, help_text='Minimum attendees allowed for booking this room', validators=[MinValueValidator(1), MaxValueValidator(1000)]),
        ),
        migrations.RunSQL(
            sql=(
                "UPDATE rooms "
                "SET max_booking_capacity = capacity "
                "WHERE max_booking_capacity = 1 AND capacity > 1;"
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
