# Generated by Django 4.2.7 on 2026-03-19 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_roomoccupiedtimerule'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='roomoccupiedtimerule',
            new_name='room_occupi_room_id_e9333a_idx',
            old_name='room_occupi_room_id_4de49e_idx',
        ),
        migrations.RenameIndex(
            model_name='roomoccupiedtimerule',
            new_name='room_occupi_rule_ty_6b5861_idx',
            old_name='room_occupi_rule_ty_c8353e_idx',
        ),
    ]
